[www]
user = rtorrent
group = rtorrent

listen = /run/php-fpm/php-fpm.sock
listen.owner = rtorrent
listen.group = rtorrent
listen.mode = 0660

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4

; PHP errors → a file in your appdata
catch_workers_output = yes
php_admin_value[error_log] = /config/log/php-error.log
php_admin_flag[log_errors] = on
